---
<<<<<<< HEAD
- hosts: clients
=======
- hosts: cluster
>>>>>>> 14bfe1abc8ec4b3a63732f8f437d7611de5647db
  vars_files:
    - vars/quobyte.yaml
  tasks:
    - name: Uninstall quobyte
      shell:
        cmd: /root/install_quobyte uninstall -f
      ignore_errors: yes
