---
- hosts: cluster
  vars_files:
    - vars/quobyte.yaml
  tasks:
    - name: Create quobyte label list
      shell: lsblk -o name,label |grep quobyte-dev |awk '{print $1}'
      register: _quobyte_labeled
    - set_fact: f_quobyte_labeled="{{ _quobyte_labeled.stdout_lines }}"
    - name: Uninstall quobyte
      shell:
        cmd: /root/install_quobyte uninstall -f
      ignore_errors: yes
    - name: Unmount quobyte devices
      shell: umount -lf /var/lib/quobyte/mnt/inspector-*
    - pause:
        seconds: 5
    - name: Clean directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/quobyte*
        - /root/.quobyte
        - /opt/quobyte*
        - /usr/lib/systemd/system/quobyte*
        - /usr/bin/*quobyte*
        - /usr/sbin/*quobyte* 
        - /etc/systemd/system/remote-fs.target.wants/quobyte*
        - /sys/fs/cgroup/systemd/system.slice/var-lib-quobyte-mnt-inspector*
        - /sys/fs/cgroup/systemd/system.slice/quobyte.mount
        - /run/lock/quobyte*
        - /run/udev/links/\x2fdisk\x2fby-label\*quobyte*
        - /dev/disk/by-label/quobyte-dev
    - name:  Clean labeled devices
      shell: wipefs -af /dev/{{ item }}
      with_items:
        - "{{ f_quobyte_labeled }}"
