- hosts: clients
  vars_files:
    - vars/quobyte.yaml
  tasks:
    - name: Download Quobyte Software for id {{ repo_id }}
      get_url:
        url: https://packages.quobyte.com/repo/3/{{ repo_id }}/install_quobyte
        dest: ~/install_quobyte
        mode: '0755'
    - name: Install Quobyte client
      shell:
        cmd: ~/install_quobyte add-client --repo-id {{ repo_id }} --registry-endpoints {{ registry }} --mount-point {{ mountpoint }}
    - name: Ensure java is installed
      package:
        name: java-1.8.0-openjdk
        state: present
    - name: Ensure chrony is installed
      package:
        name: chrony
        state: present
    - name: Ensure tuned is installed
      package:
        name: tuned
        state: present
    - name: Ensure ntp is removed
      package:
        name: ntp
        state: absent
    - name: Ensure ntpdate is removed
      package:
        name: ntpdate
        state: absent
    - name: Disable SE Linux
      shell:
        cmd: /usr/sbin/setenforce 0
      ignore_errors: yes
    - name: Ensure SELinux is set to disabled mode
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=disabled
      ignore_errors: yes
    - name: Configure quobyte client configuration
      blockinfile:
        path: /etc/quobyte/client-service.cfg
        block: |
          options=default_permissions
          disable-xattrs
    - name: Set quobyte-client tuned profile
      shell:
        cmd: /usr/sbin/tuned-adm profile quobyte-client-performance
    - name: Restart quobyte-client
      service:
        name: quobyte-client
        state: restarted
        enabled: yes
